//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace testlinq
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QLTVEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QLTVEntities1 object using the connection string found in the 'QLTVEntities1' section of the application configuration file.
        /// </summary>
        public QLTVEntities1() : base("name=QLTVEntities1", "QLTVEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLTVEntities1 object.
        /// </summary>
        public QLTVEntities1(string connectionString) : base(connectionString, "QLTVEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLTVEntities1 object.
        /// </summary>
        public QLTVEntities1(EntityConnection connection) : base(connection, "QLTVEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiSach> LoaiSaches
        {
            get
            {
                if ((_LoaiSaches == null))
                {
                    _LoaiSaches = base.CreateObjectSet<LoaiSach>("LoaiSaches");
                }
                return _LoaiSaches;
            }
        }
        private ObjectSet<LoaiSach> _LoaiSaches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhanVien> NhanViens
        {
            get
            {
                if ((_NhanViens == null))
                {
                    _NhanViens = base.CreateObjectSet<NhanVien>("NhanViens");
                }
                return _NhanViens;
            }
        }
        private ObjectSet<NhanVien> _NhanViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sach> Saches
        {
            get
            {
                if ((_Saches == null))
                {
                    _Saches = base.CreateObjectSet<Sach>("Saches");
                }
                return _Saches;
            }
        }
        private ObjectSet<Sach> _Saches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SinhVien> SinhViens
        {
            get
            {
                if ((_SinhViens == null))
                {
                    _SinhViens = base.CreateObjectSet<SinhVien>("SinhViens");
                }
                return _SinhViens;
            }
        }
        private ObjectSet<SinhVien> _SinhViens;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiSaches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiSaches(LoaiSach loaiSach)
        {
            base.AddObject("LoaiSaches", loaiSach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanViens(NhanVien nhanVien)
        {
            base.AddObject("NhanViens", nhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Saches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSaches(Sach sach)
        {
            base.AddObject("Saches", sach);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SinhViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSinhViens(SinhVien sinhVien)
        {
            base.AddObject("SinhViens", sinhVien);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTVModel", Name="LoaiSach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiSach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiSach object.
        /// </summary>
        /// <param name="loaiSach_Ma">Initial value of the LoaiSach_Ma property.</param>
        public static LoaiSach CreateLoaiSach(global::System.Int32 loaiSach_Ma)
        {
            LoaiSach loaiSach = new LoaiSach();
            loaiSach.LoaiSach_Ma = loaiSach_Ma;
            return loaiSach;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoaiSach_Ma
        {
            get
            {
                return _LoaiSach_Ma;
            }
            set
            {
                if (_LoaiSach_Ma != value)
                {
                    OnLoaiSach_MaChanging(value);
                    ReportPropertyChanging("LoaiSach_Ma");
                    _LoaiSach_Ma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoaiSach_Ma");
                    OnLoaiSach_MaChanged();
                }
            }
        }
        private global::System.Int32 _LoaiSach_Ma;
        partial void OnLoaiSach_MaChanging(global::System.Int32 value);
        partial void OnLoaiSach_MaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoaiSach_Ten
        {
            get
            {
                return _LoaiSach_Ten;
            }
            set
            {
                OnLoaiSach_TenChanging(value);
                ReportPropertyChanging("LoaiSach_Ten");
                _LoaiSach_Ten = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoaiSach_Ten");
                OnLoaiSach_TenChanged();
            }
        }
        private global::System.String _LoaiSach_Ten;
        partial void OnLoaiSach_TenChanging(global::System.String value);
        partial void OnLoaiSach_TenChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTVModel", Name="NhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhanVien object.
        /// </summary>
        /// <param name="nV_Ma">Initial value of the NV_Ma property.</param>
        public static NhanVien CreateNhanVien(global::System.Int32 nV_Ma)
        {
            NhanVien nhanVien = new NhanVien();
            nhanVien.NV_Ma = nV_Ma;
            return nhanVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NV_Ma
        {
            get
            {
                return _NV_Ma;
            }
            set
            {
                if (_NV_Ma != value)
                {
                    OnNV_MaChanging(value);
                    ReportPropertyChanging("NV_Ma");
                    _NV_Ma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NV_Ma");
                    OnNV_MaChanged();
                }
            }
        }
        private global::System.Int32 _NV_Ma;
        partial void OnNV_MaChanging(global::System.Int32 value);
        partial void OnNV_MaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NV_Ten
        {
            get
            {
                return _NV_Ten;
            }
            set
            {
                OnNV_TenChanging(value);
                ReportPropertyChanging("NV_Ten");
                _NV_Ten = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NV_Ten");
                OnNV_TenChanged();
            }
        }
        private global::System.String _NV_Ten;
        partial void OnNV_TenChanging(global::System.String value);
        partial void OnNV_TenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NV_Diachi
        {
            get
            {
                return _NV_Diachi;
            }
            set
            {
                OnNV_DiachiChanging(value);
                ReportPropertyChanging("NV_Diachi");
                _NV_Diachi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NV_Diachi");
                OnNV_DiachiChanged();
            }
        }
        private global::System.String _NV_Diachi;
        partial void OnNV_DiachiChanging(global::System.String value);
        partial void OnNV_DiachiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NV_Email
        {
            get
            {
                return _NV_Email;
            }
            set
            {
                OnNV_EmailChanging(value);
                ReportPropertyChanging("NV_Email");
                _NV_Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NV_Email");
                OnNV_EmailChanged();
            }
        }
        private global::System.String _NV_Email;
        partial void OnNV_EmailChanging(global::System.String value);
        partial void OnNV_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NV_Sodt
        {
            get
            {
                return _NV_Sodt;
            }
            set
            {
                OnNV_SodtChanging(value);
                ReportPropertyChanging("NV_Sodt");
                _NV_Sodt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NV_Sodt");
                OnNV_SodtChanged();
            }
        }
        private global::System.String _NV_Sodt;
        partial void OnNV_SodtChanging(global::System.String value);
        partial void OnNV_SodtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTVModel", Name="Sach")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sach : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sach object.
        /// </summary>
        /// <param name="sach_Ma">Initial value of the Sach_Ma property.</param>
        public static Sach CreateSach(global::System.Int32 sach_Ma)
        {
            Sach sach = new Sach();
            sach.Sach_Ma = sach_Ma;
            return sach;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sach_Ma
        {
            get
            {
                return _Sach_Ma;
            }
            set
            {
                if (_Sach_Ma != value)
                {
                    OnSach_MaChanging(value);
                    ReportPropertyChanging("Sach_Ma");
                    _Sach_Ma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Sach_Ma");
                    OnSach_MaChanged();
                }
            }
        }
        private global::System.Int32 _Sach_Ma;
        partial void OnSach_MaChanging(global::System.Int32 value);
        partial void OnSach_MaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sach_Ten
        {
            get
            {
                return _Sach_Ten;
            }
            set
            {
                OnSach_TenChanging(value);
                ReportPropertyChanging("Sach_Ten");
                _Sach_Ten = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sach_Ten");
                OnSach_TenChanged();
            }
        }
        private global::System.String _Sach_Ten;
        partial void OnSach_TenChanging(global::System.String value);
        partial void OnSach_TenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sach_Gia
        {
            get
            {
                return _Sach_Gia;
            }
            set
            {
                OnSach_GiaChanging(value);
                ReportPropertyChanging("Sach_Gia");
                _Sach_Gia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sach_Gia");
                OnSach_GiaChanged();
            }
        }
        private Nullable<global::System.Int32> _Sach_Gia;
        partial void OnSach_GiaChanging(Nullable<global::System.Int32> value);
        partial void OnSach_GiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sach_Soluong
        {
            get
            {
                return _Sach_Soluong;
            }
            set
            {
                OnSach_SoluongChanging(value);
                ReportPropertyChanging("Sach_Soluong");
                _Sach_Soluong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sach_Soluong");
                OnSach_SoluongChanged();
            }
        }
        private Nullable<global::System.Int32> _Sach_Soluong;
        partial void OnSach_SoluongChanging(Nullable<global::System.Int32> value);
        partial void OnSach_SoluongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Loaisach_Ma
        {
            get
            {
                return _Loaisach_Ma;
            }
            set
            {
                OnLoaisach_MaChanging(value);
                ReportPropertyChanging("Loaisach_Ma");
                _Loaisach_Ma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Loaisach_Ma");
                OnLoaisach_MaChanged();
            }
        }
        private Nullable<global::System.Int32> _Loaisach_Ma;
        partial void OnLoaisach_MaChanging(Nullable<global::System.Int32> value);
        partial void OnLoaisach_MaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTVModel", Name="SinhVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SinhVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SinhVien object.
        /// </summary>
        /// <param name="sV_Ma">Initial value of the SV_Ma property.</param>
        public static SinhVien CreateSinhVien(global::System.Int32 sV_Ma)
        {
            SinhVien sinhVien = new SinhVien();
            sinhVien.SV_Ma = sV_Ma;
            return sinhVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SV_Ma
        {
            get
            {
                return _SV_Ma;
            }
            set
            {
                if (_SV_Ma != value)
                {
                    OnSV_MaChanging(value);
                    ReportPropertyChanging("SV_Ma");
                    _SV_Ma = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SV_Ma");
                    OnSV_MaChanged();
                }
            }
        }
        private global::System.Int32 _SV_Ma;
        partial void OnSV_MaChanging(global::System.Int32 value);
        partial void OnSV_MaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SV_Ten
        {
            get
            {
                return _SV_Ten;
            }
            set
            {
                OnSV_TenChanging(value);
                ReportPropertyChanging("SV_Ten");
                _SV_Ten = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SV_Ten");
                OnSV_TenChanged();
            }
        }
        private global::System.String _SV_Ten;
        partial void OnSV_TenChanging(global::System.String value);
        partial void OnSV_TenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SV_Khoa
        {
            get
            {
                return _SV_Khoa;
            }
            set
            {
                OnSV_KhoaChanging(value);
                ReportPropertyChanging("SV_Khoa");
                _SV_Khoa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SV_Khoa");
                OnSV_KhoaChanged();
            }
        }
        private global::System.String _SV_Khoa;
        partial void OnSV_KhoaChanging(global::System.String value);
        partial void OnSV_KhoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SV_Lop
        {
            get
            {
                return _SV_Lop;
            }
            set
            {
                OnSV_LopChanging(value);
                ReportPropertyChanging("SV_Lop");
                _SV_Lop = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SV_Lop");
                OnSV_LopChanged();
            }
        }
        private global::System.String _SV_Lop;
        partial void OnSV_LopChanging(global::System.String value);
        partial void OnSV_LopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SV_Tensach
        {
            get
            {
                return _SV_Tensach;
            }
            set
            {
                OnSV_TensachChanging(value);
                ReportPropertyChanging("SV_Tensach");
                _SV_Tensach = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SV_Tensach");
                OnSV_TensachChanged();
            }
        }
        private global::System.String _SV_Tensach;
        partial void OnSV_TensachChanging(global::System.String value);
        partial void OnSV_TensachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SV_Loaisach
        {
            get
            {
                return _SV_Loaisach;
            }
            set
            {
                OnSV_LoaisachChanging(value);
                ReportPropertyChanging("SV_Loaisach");
                _SV_Loaisach = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SV_Loaisach");
                OnSV_LoaisachChanged();
            }
        }
        private global::System.String _SV_Loaisach;
        partial void OnSV_LoaisachChanging(global::System.String value);
        partial void OnSV_LoaisachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SV_Trangthai
        {
            get
            {
                return _SV_Trangthai;
            }
            set
            {
                OnSV_TrangthaiChanging(value);
                ReportPropertyChanging("SV_Trangthai");
                _SV_Trangthai = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SV_Trangthai");
                OnSV_TrangthaiChanged();
            }
        }
        private Nullable<global::System.Boolean> _SV_Trangthai;
        partial void OnSV_TrangthaiChanging(Nullable<global::System.Boolean> value);
        partial void OnSV_TrangthaiChanged();

        #endregion
    
    }

    #endregion
    
}
