USE [master]
GO

/****** Object:  Database [tudien]    Script Date: 08/04/2013 15:02:05 ******/
CREATE DATABASE [tudien] ON  PRIMARY 
( NAME = N'tudien', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\tudien.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tudien_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\tudien_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tudien] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tudien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tudien] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tudien] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tudien] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tudien] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tudien] SET ARITHABORT OFF 
GO

ALTER DATABASE [tudien] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tudien] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [tudien] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tudien] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tudien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tudien] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tudien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tudien] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tudien] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tudien] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tudien] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tudien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tudien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tudien] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tudien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tudien] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tudien] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tudien] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tudien] SET  READ_WRITE 
GO

ALTER DATABASE [tudien] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tudien] SET  MULTI_USER 
GO

ALTER DATABASE [tudien] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tudien] SET DB_CHAINING OFF 
GO

